### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by andywer** [andywer/webpack-blocks#134]
Hi everyone! This is gonna be the "1.0 release issue", showing the big picture, in contrast to the many small issues.

## Version number change

Since webpack 1.x has [officially been deprecated](https://webpack.github.io/docs/) I am now fine with releasing the next webpack-2-only major version as `webpack-blocks 1.0`. So if you find references to a 2.0 release, this will actually be the 1.0 release.

## Changes

- [x] Webpack 2 only, drop duplicate packages (like `extract-text` and `extract-text2`) #127
- [x] Use `module.rules` syntax #111 #124
- [x] Implement new API: #125
- [ ] Decide if the new API and its `util` parameter are fine or should be changed #125
- [ ] Drop `release/1.0` branch, rename `release/2.0` => `release/1.0`
- [ ] Make `createConfig.vanilla()` the new `createConfig()`
- [ ] Create a new package with CSS, font, image, ... loaders (because of the change above)
- [ ] Make sure that different CSS loaders work seemlessly with `node_modules` exclusion #133
- [ ] Improve sass + extract-text documentation #115
- [ ] Merge #117
- [ ] Rebase on master

(Not necessarily in that order 😉)

## Optionally

- [ ] Check which parts of `webpack-parts` might be merged into webpack-blocks #122
- [ ] Check if SASS works together with CSS modules #130

@eXon @jvanbruegge @sapegin @aaronjensen

**Comment by andywer** [comment]
Sorry for shooting ahead, but since we already had the discussion about 1.0/2.0 I figured there is not much sense in riding the now-deprecated horse much further.

You guys agree with the short summary of the 1.0 release?

**Comment by jvanbruegge** [comment]
I would add that extract text should use a post hook to work automaticly with sass (so you dont need to document anything). Would make order of sassBlock and extract-text block irrelevant

**Comment by andywer** [comment]
Good point!

**Comment by aaronjensen** [comment]
This looks good to me. I probably wouldn't rebase onto master at this point (too much risk, merge is safer and maintains history) but that's a workflow nit. I'm very 👍  on webpack 2 only.

**Comment by andywer** [comment]
True! Updated the list :)

**Comment by andywer** [comment]
Update: "Make createConfig.vanilla() the new createConfig()" and "Create a new package with CSS, font, image, ... loaders" are almost done 🎉

Idea: Now that the next LTS release of node is about to be released it might be time to drop support for node < 6.0. Would allow us to drop Babel which is not used consistently.

Objections?

**Comment by aaronjensen** [comment]
None from me 👍

**Comment by jvanbruegge** [comment]
None from me either. Destructuring makes code nicer :)

**Comment by andywer** [comment]
Just added a bullet point to "nice to have": `Create package that wraps all the most common packages, so user does not have to manage dozens of single webpack-blocks packages`

This is an idea I had in my mind for some weeks now: The modularity of webpack-blocks is a nice feature, but having to manage a dozen `@webpack-blocks/*` devDependencies does not look very elegant. So a package that exports all the most common blocks might be a nice solution.

```diff
+ const { createConfig, env, entryPoint, setOutput, sourceMaps, css, file, babel, devServer } = require('webpack-blocks')
- const { createConfig, env, entryPoint, setOutput, sourceMaps } = require('@webpack-blocks/webpack')
- const { css, file } = require('@webpack-blocks/assets')
- const babel = require('@webpack-blocks/babel6')
- const devServer = require('@webpack-blocks/dev-server')

module.exports = createConfig([ /* ... */ ])
```
```diff
{
  "devDependencies": {
+   "webpack-blocks": "^1.0.0",
-   "@webpack-blocks/assets": "^1.0.0",
-   "@webpack-blocks/babel6": "^1.0.0",
-   "@webpack-blocks/dev-server": "^1.0.0",
-   "@webpack-blocks/webpack": "^1.0.0",
    "webpack": "^2.0.0"
  }
}
```

Fewer dependencies in the app, less effort keeping block versions in sync (e.g. `@webpack-blocks/webpack v1.0` together with `@webpack-blocks/dev-server v0.4` will crash), easier to switch to new major versions.

Could also be added after the 1.0 release, though. And maybe it should be, since there are still more important things left to do.

**Comment by jvanbruegge** [comment]
Yes, this may also increase adoption, because simply from a psychological view a single dependency is less scary than a dozend

**Comment by stevenjlho** [comment]
This is a nice feature.

**Comment by Wenqer** [comment]
@andywer i suggest to stay babel in the separate package, because not all web devs use it now, for example: typescript devs, electron devs, guys who support only latest versions of chrome/firefox

**Comment by jvanbruegge** [comment]
It does not matter if it is included or not. Just dont use it. It's a devDependency, so size is not a problem.
I would include all official blocks.

**Comment by andywer** [comment]
@Wenqer @jvanbruegge You both got valid points, but I'd say the truth lies somewhere in between. We should ship many of the official blocks, because otherwise it won't be very useful and as Jan pointed out, dev dependencies' size does not matter much.

On the other hand I would probably not want to include the `elm` block, for instance, since it will install quite a lot of stuff that the majority of people won't use.

I suggest including both the `babel` and `typescript` block. Otherwise it's going to be neither of them (that would be sad) or a decision React vs Angular 😉

**Comment by jvanbruegge** [comment]
Ok, yeah I agree, didn't think of the elm block

**Comment by andywer** [comment]
A few quick `npm publish` for me, but a big step forward for webpack-blocks:

The alpha version of webpack-blocks v1.0 is published! 🎉

Install using `npm install --save-dev @webpack-blocks/webpack@next ...` or using the new convenience package `npm install --save-dev webpack-blocks@next`.

Give it a try and report any issues you might encounter. Should be fairly stable for an "alpha", though 😉

Remember that there were breaking changes in the core API. All blocks in this repo have been updated, but third-party blocks or your custom blocks won't work until they are updated as well.

**Comment by jvanbruegge** [comment]
Maybe tick the assets block and the convenience block in your list :)

**Comment by andywer** [comment]
Ohh, of course :)

I won't tick the assets preset, since there is the block, but not a preset. Btw, I am not sure if we actually need a preset for that.

**Comment by andywer** [comment]
Pinging @bkonkle, @diegohaz, @foxbunny, since they will need to update their blocks. But don't worry, this is like a first official heads-up. A short migration guide will follow (don't worry, it's not hard to update).

**Comment by bkonkle** [comment]
Thanks for the advance warning!

--

Brandon Konkle

Phone: (720) 239-2573

Twitter: 
http://twitter.com/bkonkle http://ecliptic.io/

On Mon, May 08, 2017 at 10:09 AM Andy Wermke

<
mailto:Andy Wermke <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Pinging
https://github.com/bkonkle
,
https://github.com/diegohaz
,
https://github.com/foxbunny
, since they will need to update their blocks. But don't worry, this is like a first official heads-up. A short migration guide will follow (don't worry, it's not hard to update).

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/andywer/webpack-blocks/issues/134#issuecomment-299912667
, or

**Comment by foxbunny** [comment]
@andywer I see there are now somewhat non-essential blocks like elm block. What is the official policy regarding contributed blocks? Is it preferred that developers contribute to this repository, or maintain their own?

**Comment by andywer** [comment]
@foxbunny Good question. My current approach is:

Open a PR if you think the block is worth being put in the official repository and we will have a look at it and decide if it makes sense to merge 😉

Generally I'd say that most framework-related blocks are probably not supposed to be part of the official repo, except for maybe very popular React or Angular stuff, since they are very dominant.

Elm is on the very edge of what I'd say should be part of the main repo. But everything is discussable :)

I hope that clarifies things at least a little bit!

**Comment by foxbunny** [comment]
Alright, sounds good.

**Comment by dmitmel** [comment]
Is there any progress in this release?

**Comment by andywer** [comment]
We should ship it! :shipit:

I don't see any blockers. Better docs would be nice, but shouldn't block the release.

**Comment by stevenjlho** [comment]
I think we shouldn’t add more feature before 1.0 release. And improve document detail.

**Comment by dmitmel** [comment]
> We should ship it!

@andywer Is 1.0 release ready to be published to NPM?

**Comment by andywer** [comment]
I think v1.0 is ready to be published.

TypeScript typings would be really nice to have, but who knows how the long that will take (and I have very little time at the moment).

@all **Does anyone see a reason not to release v1.0?**

**Comment by dmitmel** [comment]
@andywer I think it's time to finally release v1.0 and to start working on v2.0.

**Comment by zcei** [comment]
I'm still up for providing some first typings as soon as we've settled for naming we want to proceed with.
Until then: release the v1.0

**Comment by andywer** [comment]
Left a comment in the [typings issue](https://github.com/andywer/webpack-blocks/issues/246#issuecomment-376415750).

Yeah, I should just block some time later this week and :shipit: v1.0.
I would schedule it for release on Thursday night (so round about 19:00 UTC).
